### ISSUE TITLE
INFOGRAFIA_MAYRA_GLEZ_1AS

### ISSUE THREAD

**Issue by mayraglez917** [SistemasTecTlaxiaco/infografia-mayraglez917#2]
INFOGRAFIA_MAYRA_GLEZ_1AS
[INFOGRAFIA_MAYRA_GLEZ_1AS.pdf](https://github.com/SistemasTecTlaxiaco/infografia-mayraglez917/files/12501970/INFOGRAFIA_MAYRA_GLEZ_1AS.pdf)

**Comment by 23620031** [comment]
REDACCIÓN Y ORTOGRAFÍA 10/10
EXPOSICIÓN DE IDEAS CENTRALES 15/15
ORGANIZACIÓN DE LA INFORMACIÓN 15/15
USO DE IMÁGENES Y COLORES 15/15
PRESENTACIÓN VISUAL 15/15
REFERENCIAS 15/15
PRESENTACIÓN 15/15

CALIFICADO POR EL EQUIPO DE "LÓPEZ DOMÍNGUEZ ISAÍAS BRAYAN"

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
